# Generated by Django 4.2.7 on 2026-05-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='farm_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farm_size_acres',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Authority / Police'), ('admin', 'System Admin')], default='citizen', max_length=20),
        ),
    ]
