# Generated by Django 4.2.7 on 2026-05-18 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def nullify_empty_phones(apps, schema_editor):
    """
    Convert empty phone strings → NULL, and deduplicate phone numbers.
    For duplicate non-empty phones, keep the one belonging to the lowest
    user pk and NULL-out the rest (dev-data cleanup only).
    """
    User = apps.get_model('accounts', 'User')
    # 1. Empty → NULL
    User.objects.filter(phone='').update(phone=None)
    # 2. Deduplicate: for each phone that appears more than once, keep the
    #    first (lowest id) and null-out the rest.
    seen = {}
    for u in User.objects.exclude(phone=None).order_by('id'):
        if u.phone in seen:
            u.phone = None
            u.save(update_fields=['phone'])
        else:
            seen[u.phone] = u.pk


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_farm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_anonymous_reporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        # Step 1: Allow NULL first (without unique) so we can nullify empty strings
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        # Step 2: Convert '' → NULL now that the column allows NULL
        migrations.RunPython(nullify_empty_phones, migrations.RunPython.noop),
        # Step 3: Add the UNIQUE constraint (now safe because no duplicate NULLs)
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('phone_verify', 'Phone Verification'), ('login', 'Login OTP')], default='phone_verify', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
