# Generated by Django 4.2.7 on 2026-04-21 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('facility_type', models.CharField(choices=[('cold_storage', 'Cold Storage'), ('warehouse', 'Warehouse'), ('market', 'Agricultural Market (APMC)'), ('distribution', 'Distribution Center'), ('processing', 'Processing Unit')], max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity_tons', models.FloatField(default=0)),
                ('available_capacity_tons', models.FloatField(default=0)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_hours', models.CharField(default='6AM - 8PM', max_length=100)),
                ('accepted_crops', models.TextField(blank=True, help_text='Comma-separated list of accepted crops')),
                ('price_per_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Storage Facility',
                'verbose_name_plural': 'Storage Facilities',
            },
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('crop_type', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains / Cereals'), ('pulses', 'Pulses'), ('dairy', 'Dairy Products'), ('poultry', 'Poultry / Eggs'), ('spices', 'Spices'), ('flowers', 'Flowers'), ('other', 'Other')], max_length=30)),
                ('crop_name', models.CharField(max_length=200)),
                ('quantity_tons', models.FloatField()),
                ('is_perishable', models.BooleanField(default=False)),
                ('requires_cold_storage', models.BooleanField(default=False)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('pickup_date', models.DateTimeField()),
                ('preferred_destination_type', models.CharField(blank=True, choices=[('cold_storage', 'Cold Storage'), ('warehouse', 'Warehouse'), ('market', 'Agricultural Market (APMC)'), ('distribution', 'Distribution Center'), ('processing', 'Processing Unit')], max_length=30)),
                ('suggested_route', models.JSONField(blank=True, null=True)),
                ('estimated_distance_km', models.FloatField(blank=True, null=True)),
                ('estimated_duration_hours', models.FloatField(blank=True, null=True)),
                ('route_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('route_suggested', 'Route Suggested'), ('confirmed', 'Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_requests', to='transport.storagefacility')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('waypoint_type', models.CharField(default='checkpoint', max_length=50)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='transport.transportrequest')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
