# Generated by Django 4.2.7 on 2026-05-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_add_rag_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='rag_corrected',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rag_validated',
        ),
    ]
