# Generated by Django 4.2.7 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_remove_rag_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintevidence',
            name='ai_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('complaint_update', 'Complaint Update'), ('new_assignment', 'New Assignment'), ('system', 'System Notification')], max_length=30),
        ),
    ]
